window.TERRAUGUSTA_DATA.articles.push(...[
{"id":"pedras-peregrinas","title":"Pedras Peregrinas","type":"Local","region":"Aelvar","status":"CANON","summary":"Localização canonizada de Aelvar.","aliases":[],"tags":["marco"],"sections":{"Estado":"Local confirmado; lore detalhado ainda é escasso."},"related":["aelvar"]},
{"id":"galerias-barag-dur","title":"Galerias de Barag-Dur","type":"Local","region":"Aelvar","status":"CANON","summary":"Localização subterrânea/mineral canonizada em Aelvar.","aliases":[],"tags":["galerias"],"sections":{"Estado":"Nome e existência confirmados; detalhes podem ser expandidos posteriormente."},"related":["aelvar"]},
{"id":"orunai","title":"Orunai","type":"Povo","region":"Aelvar","status":"CANON","summary":"Povo humano nômade/peregrino de Aelvar, ligado à história de Aida.","aliases":[],"tags":["nomades","aida"],"sections":{"Território":"Percorrem rotas da região central de Aelvar, incluindo áreas ao pé da Cordilheira Rasga-Céu.","Figura ligada":"Aida pertence a esse contexto cultural."},"related":["aida","cordilheira-rasga-ceu"]},
{"id":"verdoria","title":"Verdória","type":"Região","region":"Verdória","status":"CANON","summary":"Ilha Verde de Terraugusta, com grande concentração de cidades, clãs, regiões selvagens e conflitos históricos.","aliases":["Ilha Verde"],"tags":["ilha","verdoria"],"sections":{"Locais":"Inclui Brent, Bek'Ground, Escarpa Negra, Lunoir, Vila de Leite, Dite, Dun'Bhoramm, Krep'Ga, Morgvar, Morte Súbita, Morro Redondo e outros pontos.","Mapa":"A costa aprovada deve ser preservada em futuras revisões cartográficas."},"related":["brent","escarpa-negra","vargari","morgvar"]},
{"id":"brent","title":"Brent","type":"Assentamento","region":"Verdória","status":"CANON","summary":"Cidade importante de Verdória que assume papel militar de destaque após Escarpa Negra.","aliases":[],"tags":["cidade","militar"],"sections":{"Relações":"Mantém aliança histórica com Bek'Ground desde que Anthony cedeu terras a Antonidas."},"related":["bekground","escarpa-negra"]},
{"id":"bekground","title":"Bek'Ground","type":"Assentamento","region":"Verdória","status":"CANON","summary":"Cidade aliada historicamente a Brent.","aliases":[],"tags":["cidade","antonidas"],"sections":{"História":"Antonidas, um Asteliano que viveu entre os Drueggar, tornou-se prefeito de Bek'Ground."},"related":["brent"]},
{"id":"escarpa-negra","title":"Escarpa Negra","type":"Assentamento","region":"Verdória","status":"CANON","summary":"Fortaleza/cidade associada a campanhas militares, ao mausoléu de Charlotte Sullivan e a conflitos religiosos.","aliases":[],"tags":["fortaleza","militar"],"sections":{"Campanhas":"Foi polo militar em Fora do Domo antes de Brent assumir maior centralidade.","Memória":"Abriga o mausoléu de Charlotte Sullivan."},"related":["brent","ulrich-iii","arautos-do-eclipse"]},
{"id":"lunoir","title":"Lunoir","type":"Assentamento","region":"Verdória","status":"CANON","summary":"Domínio vampírico ligado aos Morros da Bruxaria.","aliases":[],"tags":["vampiros","odette"],"sections":{"Sucessão":"A Condessa Odette de Lunoir está ligada à linhagem; Carmesine Lunoir atua como fantoche atual. A sucessão segue pela filha mais velha."},"related":["morros-da-bruxaria"]},
{"id":"dite","title":"Dite","type":"Assentamento","region":"Verdória","status":"CANON","summary":"Cidade tiefling de Verdória.","aliases":[],"tags":["tieflings","cidade"],"sections":{"Taverna":"A taverna local se chama Inferninho e seu taverneiro é o tiefling Dante."},"related":["inferninho","verdoria"]},
{"id":"inferninho","title":"Inferninho","type":"Local","region":"Verdória","status":"CANON","summary":"Taverna de Dite administrada por Dante.","aliases":[],"tags":["taverna","dite"],"sections":{"Equipe":"Taverneiro: Dante, tiefling."},"related":["dite"]},
{"id":"morgvar","title":"Morgvar","type":"Região","region":"Verdória","status":"CANON","summary":"Região florestal de Verdória anteriormente chamada Vale Divino.","aliases":["Vale Divino (nome antigo)"],"tags":["floresta","rio"],"sections":{"Geografia":"Um rio separa/estrutura a região. Morte Súbita fica a leste de Morgvar."},"related":["morte-subita","verdoria"]},
{"id":"morte-subita","title":"Morte Súbita","type":"Assentamento","region":"Verdória","status":"CANON","summary":"Cidade situada a leste de Morgvar.","aliases":[],"tags":["cidade","morgvar"],"sections":{"Localização":"Fica a leste de Morgvar."},"related":["morgvar"]},
{"id":"morros-da-bruxaria","title":"Morros da Bruxaria","type":"Região","region":"Verdória","status":"CANON","summary":"Região de Verdória associada ao domínio vampírico de Lunoir.","aliases":[],"tags":["morros","vampiros"],"sections":{"Relação":"Funciona como a 'Transilvânia' regional ligada a Lunoir."},"related":["lunoir"]},
{"id":"burgo-celeste","title":"Burgo Celeste","type":"Assentamento","region":"Verdória","status":"CANON","summary":"Alcunha popular estabelecida para uma cidade de Verdória; o nome oficial definitivo ainda está em discussão.","aliases":["Vesperlumia (proposta de nome oficial)"],"tags":["cidade","alcunha"],"sections":{"Nomenclatura":"Burgo Celeste é a alcunha usada pelos plebeus. 'Vesperlumia' permanece como proposta de nome oficial, não tratada aqui como decisão final."},"related":["verdoria","vesperlumia"]}
]);
