window.TERRAUGUSTA_DATA.articles.push(...[
{"id":"vesperlumia","title":"Vesperlumia","type":"Nome provisório","region":"Verdória","status":"PROVISÓRIO","summary":"Proposta de nome oficial para a cidade popularmente chamada Burgo Celeste.","aliases":[],"tags":["nome","burgo celeste"],"sections":{"Estado":"Não substituir Burgo Celeste como fato definitivo até nova canonização explícita."},"related":["burgo-celeste"]},
{"id":"vargari","title":"Vargari","type":"Povo/Fação","region":"Verdória","status":"CANON","summary":"Povo organizado em clãs, com saques no verão e assembleia em Moegvar durante o inverno.","aliases":[],"tags":["clans","moegvar"],"sections":{"Ciclo anual":"No verão realizam saques; no inverno reúnem-se em Moegvar, depósito e local de assembleia.","Projeto de sinalização":"Skallvar obtêm recursos; Hriskar cuidam de comida, barracas e cobertores; Draugren fazem segurança e primeiros socorros; Jarnulf fabricam placas, equipamentos e ferramentas; Vintermark exploram a rota e produzem mapas."},"related":["skallvar","hriskar","draugren","jarnulf","vintermark"]},
{"id":"skallvar","title":"Clã Skallvar","type":"Clã","region":"Verdória","status":"CANON","summary":"Clã do Lobo, o mais prestigioso entre os Vargari.","aliases":[],"tags":["vargari","lobo"],"sections":{"Especialidade":"Em projetos coletivos, obtém recursos, inclusive por meio de saques."},"related":["vargari"]},
{"id":"hriskar","title":"Clã Hriskar","type":"Clã","region":"Verdória","status":"CANON","summary":"Clã do Carneiro ligado à logística.","aliases":[],"tags":["vargari","logistica"],"sections":{"Especialidade":"Fornece comida, barracas e cobertores para trabalhadores."},"related":["vargari"]},
{"id":"draugren","title":"Clã Draugren","type":"Clã","region":"Verdória","status":"CANON","summary":"Clã Vargari especializado em segurança e primeiros socorros.","aliases":[],"tags":["vargari","seguranca"],"sections":{"Especialidade":"Protege trabalhadores de ameaças naturais e presta primeiros socorros em acidentes."},"related":["vargari"]},
{"id":"jarnulf","title":"Clã Jarnulf","type":"Clã","region":"Verdória","status":"CANON","summary":"Clã Vargari ligado à produção de placas, equipamentos e ferramentas.","aliases":[],"tags":["vargari","ferramentas"],"sections":{"Especialidade":"Confecciona placas e equipamentos especializados."},"related":["vargari"]},
{"id":"vintermark","title":"Clã Vintermark","type":"Clã","region":"Verdória","status":"CANON","summary":"Trailblazers dos Vargari.","aliases":[],"tags":["vargari","exploracao"],"sections":{"Especialidade":"Explora regiões, determina rotas e prepara mapas para projetos coletivos."},"related":["vargari"]},
{"id":"safrath","title":"Safrath","type":"Região","region":"Safrath","status":"CANON","summary":"Ilha Amarela de Terraugusta, marcada por desertos, rotas marítimas, centros de conhecimento e disputas pelo controle da água.","aliases":["Ilha Amarela"],"tags":["ilha","deserto"],"sections":{"Locais":"Inclui Porto Zenith, Mar de Vidro, Al-Fujayra, Forte Riad, Academia Arcana, Grande Biblioteca e Espinha de Unalzath.","Política":"Hashin, sultão e ex-escravo, aboliu a escravidão."},"related":["porto-zenith","al-fujayra","nornando-de-feronha"]},
{"id":"porto-zenith","title":"Porto Zenith","type":"Assentamento","region":"Safrath","status":"CANON","summary":"Porto de Safrath com relações mais abertas com Al-Fujayra após mudanças políticas.","aliases":[],"tags":["porto","safrath"],"sections":{"Relações":"A relação com Al-Fujayra tornou-se mais aberta no período de Hashin."},"related":["al-fujayra","safrath"]},
{"id":"al-fujayra","title":"Al-Fujayra","type":"Assentamento","region":"Safrath","status":"CANON","summary":"Cidade da costa centro-leste de Safrath.","aliases":[],"tags":["cidade","costa"],"sections":{"Localização":"Costa centro-leste de Safrath."},"related":["porto-zenith","safrath"]},
{"id":"mar-de-vidro","title":"Mar de Vidro","type":"Local natural","region":"Safrath","status":"CANON","summary":"Região de Safrath posicionada acima de Unalzath e reduzida em escala nas revisões cartográficas mais recentes.","aliases":[],"tags":["deserto","mapa"],"sections":{"Cartografia":"Deve aparecer menor do que em versões antigas do mapa."},"related":["safrath"]},
{"id":"nornando-de-feronha","title":"Nornando de Feronha","type":"Região","region":"Nornando de Feronha","status":"CANON","summary":"Território separado ao norte de Safrath, com ilhas, portos, navios voadores e tecnologia bélica rudimentar.","aliases":[],"tags":["ilhas","navios voadores"],"sections":{"Grafia":"A forma canônica é Feronha, sem RR.","Sucessão portuária":"Se o regente se mostra incapaz de controlar os portos, o capitão do porto assume."},"related":["forte-risca-faca","safrath"]},
{"id":"forte-risca-faca","title":"Forte Risca-Faca","type":"Local","region":"Nornando de Feronha","status":"CANON","summary":"Forte de Nornando de Feronha.","aliases":[],"tags":["forte"],"sections":{"Estado":"Local confirmado no mapa de Nornando."},"related":["nornando-de-feronha"]}
]);
