window.TERRAUGUSTA_DATA.articles.push(...[
  {"id":"aelvar","title":"Aelvar","type":"Região","region":"Aelvar","status":"CANON","summary":"Ilha Branca de Terraugusta, com Corellian a oeste, Lyravelle a leste e a Cordilheira Rasga-Céu no norte.","aliases":["Ilha Branca"],"tags":["ilha","aelvar"],"sections":{"Geografia":"A Cordilheira Rasga-Céu ocupa a costa norte. Corellian fica a oeste, próxima a Rocha do Leopardo. Lyravelle ocupa o leste em torno do lago conhecido popularmente como Água Clara.","Conflitos":"A região inclui tensões envolvendo Joia de Arcturos, Lyravelle, Rocha do Leopardo e movimentos de resistência."},"related":["corellian","lyravelle","joia-de-arcturos","rocha-do-leopardo","orunai"]},
  {"id":"corellian","title":"Corellian","type":"Assentamento","region":"Aelvar","status":"CANON","summary":"Cidade do oeste de Aelvar fundada por William Corell, próxima a Rocha do Leopardo.","aliases":[],"tags":["cidade","conselho"],"sections":{"História":"Corellian foi fundada por William Corell.","Conselho":"Yavanna, Charlotte de Corellian e Knowles aparecem ligados ao conselho. Charlotte atua como chefe da guarda."},"related":["charlotte-de-corellian","rocha-do-leopardo","aelvar"]},
  {"id":"myrtholone","title":"Myrtholone","type":"Assentamento","region":"Aelvar","status":"CANON","summary":"Centro de guerrilha em Aelvar com apoio secreto local e participação ocasional da Inquisição.","aliases":[],"tags":["guerrilha","halflings"],"sections":{"Governo":"O prefeito é Barnaby Summerbloom.","Resistência":"Lineon Flintwind mantém a imagem pública de xerife incompetente enquanto o sistema local de 'prende e solta' favorece guerrilheiros."},"related":["barnaby-summerbloom","cordelia-summerbloom","lineon-flintwind"]},
  {"id":"lyravelle","title":"Lyravelle","type":"Assentamento","region":"Aelvar","status":"CANON","summary":"Cidade élfica no leste de Aelvar, erguida num planalto junto ao lago de águas excepcionalmente claras.","aliases":["Aeliryn (nome antigo/obsoleto)"],"tags":["elfos","cidade","agua clara"],"sections":{"Nome":"O nome Lyravelle homenageia um bardo élfico que tocava lira junto às águas e convenceu outros elfos a se estabelecerem ali.","Lago":"No verão, a neve da Cordilheira Rasga-Céu derrete e corre para leste, enchendo o lago do planalto. O tom azul mais claro levou outros povos a chamar o lugar de Água Clara.","Correção canônica":"Lyravelle substitui o antigo nome Aeliryn no cânone atual."},"related":["agua-clara","cordilheira-rasga-ceu","joia-de-arcturos"]},
  {"id":"agua-clara","title":"Água Clara","type":"Local natural","region":"Aelvar","status":"CANON","summary":"Nome popular dado por outros povos ao lago/área de águas azul-claras junto a Lyravelle.","aliases":[],"tags":["lago","lyravelle"],"sections":{"Origem":"O nome vem da coloração mais clara das águas.","Hidrologia":"É alimentado sazonalmente pelo degelo da Cordilheira Rasga-Céu."},"related":["lyravelle","cordilheira-rasga-ceu"]},
  {"id":"joia-de-arcturos","title":"Joia de Arcturos","type":"Assentamento","region":"Aelvar","status":"CANON","summary":"Cidade de Aelvar ligada ao culto de Arcturos e a uma fronteira historicamente tensa com o poder élfico oriental.","aliases":[],"tags":["cidade","arcturos","fronteira"],"sections":{"Fronteira":"A região viveu tensão ativa com o poder élfico do leste.","Taverna":"A taverna Cervo Folheado é administrada por Irwin Galhopedra; Mirna Folhaverde atua como cozinheira."},"related":["arcturos","aida","lambert","cervo-folheado"]},
  {"id":"cervo-folheado","title":"Cervo Folheado","type":"Local","region":"Aelvar","status":"CANON","summary":"Taverna de Joia de Arcturos.","aliases":[],"tags":["taverna","joia de arcturos"],"sections":{"Equipe":"Taverneiro: Irwin Galhopedra. Cozinheira: Mirna Folhaverde."},"related":["joia-de-arcturos"]},
  {"id":"rocha-do-leopardo","title":"Rocha do Leopardo","type":"Região","region":"Aelvar","status":"CANON","summary":"Potência do oeste de Aelvar, também abreviada como RdL.","aliases":["RdL"],"tags":["reino","aelvar"],"sections":{"Símbolos":"Pinheiro-Rei e coroa preta aparecem ligados à identidade local.","Conflitos":"A história recente inclui guerra, traição dinástica e campanhas militares envolvendo Hrothgard e Fuuma."},"related":["corellian","fuuma"]},
  {"id":"cordilheira-rasga-ceu","title":"Cordilheira Rasga-Céu","type":"Local natural","region":"Aelvar","status":"CANON","summary":"Cordilheira que domina a costa norte de Aelvar.","aliases":[],"tags":["montanhas","degelo"],"sections":{"Hidrologia":"Seu degelo de verão alimenta cursos d'água que seguem para leste, incluindo o lago de Lyravelle."},"related":["aelvar","lyravelle","agua-clara"]},
  {"id":"lago-rivendyne","title":"Lago Rivendyne","type":"Local natural","region":"Aelvar","status":"CANON","summary":"Maior fonte de água potável de Aelvar, capaz de abastecer outros reinos.","aliases":[],"tags":["lago","agua"],"sections":{"Importância":"É uma infraestrutura natural estratégica pela disponibilidade de água potável."},"related":["aelvar"]},
  {"id":"mosteiro-folha-branca","title":"Mosteiro da Folha Branca","type":"Local","region":"Aelvar","status":"CANON","summary":"Localização canonizada de Aelvar.","aliases":[],"tags":["mosteiro"],"sections":{"Estado":"Local confirmado no mapa/cânone; detalhes adicionais ainda podem ser desenvolvidos."},"related":["aelvar"]}
]);
