window.TERRAUGUSTA_DATA.articles.push(...[
{"id":"nova-krepga","title":"Nova Krep'Ga","type":"Região","region":"Nova Krep'Ga","status":"CANON","summary":"Arquipélago de cinco ilhas fundado por refugiados pescadores de Krep'Ga.","aliases":[],"tags":["arquipelago","refugiados"],"sections":{"Origem":"Há cerca de 150 anos, ataques de exércitos orcs treinados levaram habitantes de Krep'Ga a fugir pelo mar e fundar Nova Krep'Ga.","Ilhas":"Pedra da Boaventura, Maré Farta, Dunas do Ocaso, Mata da Crina e Destino Final. Duas são habitadas; as duas últimas permanecem selvagens."},"related":["pedra-da-boaventura","mare-farta","dunas-do-ocaso"]},
{"id":"pedra-da-boaventura","title":"Pedra da Boaventura","type":"Ilha","region":"Nova Krep'Ga","status":"CANON","summary":"Ilha mais rica de Nova Krep'Ga, governada pelo ditador Marc e com acesso restrito.","aliases":[],"tags":["ilha","marc"],"sections":{"Sociedade":"É a ilha mais rica do arquipélago e possui acesso restrito."},"related":["nova-krepga"]},
{"id":"mare-farta","title":"Maré Farta","type":"Ilha","region":"Nova Krep'Ga","status":"CANON","summary":"Segunda ilha habitada de Nova Krep'Ga, associada à população comum.","aliases":[],"tags":["ilha","povo"],"sections":{"Estado":"Uma das duas ilhas habitadas."},"related":["nova-krepga"]},
{"id":"dunas-do-ocaso","title":"Dunas do Ocaso","type":"Ilha","region":"Nova Krep'Ga","status":"CANON","summary":"Ilha de dunas e lagoas ligada a um Aboleth e às histórias de Sandro e Jane.","aliases":[],"tags":["ilha","aboleth"],"sections":{"Aventura":"Possui um Aboleth e conexões narrativas com Sandro e Jane."},"related":["nova-krepga","sandro-livingstone"]},
{"id":"nova-astelia","title":"Nova Astelia","type":"Região/Mundo","region":"Nova Astelia","status":"CANON","summary":"Astelia após o resgate de 1492: povos reconstruindo sociedades enquanto terraugustenses chegam, exploram e reivindicam espaço.","aliases":["Astelia"],"tags":["astelia","1492","resgate"],"sections":{"História":"Astelia definhou por cerca de 3.000 anos. Dragões dominaram e caíram; povos sobreviveram e reconstruíram.","Contato":"A Pedra do Mundo completa permitiu o resgate em 1492. A chegada de terraugustenses gerou tensões de exploração, ocupação e linguagem."},"related":["pedra-do-mundo","fora-do-domo","gonzalopolis"]},
{"id":"gonzalopolis","title":"Gonzalópolis","type":"Acampamento","region":"Nova Astelia","status":"CANON","summary":"Acampamento terraugustense em Nova Astelia ligado aos Riconautas e financiado por Rico Gonzalez.","aliases":[],"tags":["acampamento","riconautas"],"sections":{"Financiamento":"Financiado por Rico Gonzalez."},"related":["nova-astelia"]},
{"id":"aida","title":"Aida","type":"Personagem","region":"Aelvar","status":"CANON","summary":"Paladina de Arcturos ligada aos Orunai e a uma luta por independência e causa social.","aliases":[],"tags":["paladina","arcturos","orunai"],"sections":{"Origem":"Ligada ao povo Orunai.","Família":"Seu primo Lambert foi preso antes de Aida tornar-se paladina e acabou translocado para Agrestia."},"related":["orunai","arcturos","lambert"]},
{"id":"lambert","title":"Lambert","type":"Personagem","region":"Aelvar","status":"ABERTO","summary":"Primo de Aida, preso e posteriormente translocado para Agrestia; seu destino atual permanece desconhecido.","aliases":[],"tags":["prisioneiro","agrestia"],"sections":{"Prisão":"Foi preso cerca de dois meses antes de Aida tornar-se paladina, durante o período de Arautos do Eclipse.","Destino":"Foi translocado para Agrestia durante Fora do Domo. O paradeiro atual é um gancho aberto."},"related":["aida","linnus","fora-do-domo"]},
{"id":"linnus","title":"Linnus","type":"Personagem","region":"Aelvar","status":"CANON","summary":"Meio-elfo druida do Círculo da Lua, nascido nas pradarias geladas de Aelvar e preso após ajudar Aurea.","aliases":[],"tags":["druida","circulo da lua","aurea"],"sections":{"Origem":"Nasceu nas pradarias geladas de Aelvar, longe de Lyravelle.","Aurea":"Ajudou a dragão dourada Aurea a escapar de guardas élficos e ficou para trás para permitir a fuga."},"related":["aurea","lambert"]},
{"id":"aurea","title":"Aurea","type":"Personagem","region":"Aelvar","status":"CANON","summary":"Dragão dourada que assumia forma de elfa de cabelos e olhos dourados.","aliases":[],"tags":["dragao dourado","elfa"],"sections":{"Linnus":"Amiga de Linnus desde a infância; revelou sua forma verdadeira ao combater guardas que a caçavam."},"related":["linnus"]},
{"id":"charlotte-de-corellian","title":"Charlotte de Corellian","type":"Personagem","region":"Aelvar","status":"CANON","summary":"Chefe da guarda de Corellian e figura ligada ao conselho local.","aliases":[],"tags":["corellian","guarda"],"sections":{"Cargo":"Chefe da guarda; anteriormente ligada aos Arautos."},"related":["corellian"]},
{"id":"barnaby-summerbloom","title":"Barnaby Summerbloom","type":"Personagem","region":"Aelvar","status":"CANON","summary":"Prefeito halfling de Myrtholone.","aliases":[],"tags":["halfling","prefeito"],"sections":{"Governo":"Mantém apoio secreto à guerrilha local."},"related":["myrtholone","cordelia-summerbloom"]}
]);
