window.TERRAUGUSTA_DATA.articles.push(...[
{"id":"cordelia-summerbloom","title":"Cordelia Summerbloom","type":"Personagem","region":"Aelvar","status":"CANON","summary":"Halfling de 115 anos, warlock Celestial de Elpisar, conhecida por sua resiliência e por guiar combatentes com uma lanterna.","aliases":[],"tags":["halfling","warlock","elpisar","chiquinho"],"sections":{"Aparência":"Longos cabelos grisalhos em duas tranças.","Pacto":"Pacto Celestial com Elpisar, associado à Esperança.","Familiar":"Uma cacatua chamada Chiquinho."},"related":["myrtholone","barnaby-summerbloom"]},
{"id":"lineon-flintwind","title":"Lineon Flintwind","type":"Personagem","region":"Aelvar","status":"CANON","summary":"Xerife halfling de Myrtholone e amigo do prefeito Barnaby Summerbloom.","aliases":[],"tags":["xerife","halfling"],"sections":{"Método":"O padrão de 'prende e solta' guerrilheiros ajuda a sustentar a resistência enquanto sua imagem pública parece incompetente para observadores externos."},"related":["myrtholone","barnaby-summerbloom"]},
{"id":"fuuma","title":"Fuuma","type":"Personagem","region":"Aelvar","status":"CANON","summary":"Monja humana, esposa e general ligada à liderança de Rocha do Leopardo.","aliases":[],"tags":["monja","general"],"sections":{"Campanhas":"Participa das relações entre Rocha do Leopardo, Corellian e os Arautos."},"related":["rocha-do-leopardo","corellian"]},
{"id":"sandro-livingstone","title":"Sandro Livingstone","type":"Personagem","region":"Verdória","status":"CANON","summary":"Antigo Sandro Protegor; abandonou a nobreza e adotou o sobrenome de sua esposa Jane.","aliases":["Sandro Protegor"],"tags":["paladino","jane","livingstone"],"sections":{"Nome":"Sandro Protegor e Sandro Livingstone representam fases diferentes da vida do personagem.","Família":"Casou-se com Jane e adotou Livingstone ao sair da nobreza."},"related":["dunas-do-ocaso"]},
{"id":"ulrich-iii","title":"Ulrich III","type":"Personagem","region":"Sacralia","status":"CANON","summary":"Figura da Inquisição em Sacralia, associado a discurso de fé firme e à condenação da laicidade de Escarpa Negra.","aliases":[],"tags":["inquisicao","sacralia"],"sections":{"Cruzada":"Anuncia uma cruzada no contexto do conflito religioso e político."},"related":["sacralia","escarpa-negra"]},
{"id":"herois-improvaveis","title":"Heróis Improváveis","type":"Campanha","region":"Geral","status":"CANON","summary":"Campanha situada em 1462, incluindo o banquete bárbaro, Mephistopheles e o ataque do dragão verde à Vila de Leite.","aliases":[],"tags":["campanha","1462"],"sections":{"Eventos":"Daffar invoca Mephistopheles; Zorg permanece; o pai de Zorg morre; Sandro torna-se paladino de Mephistopheles; um dragão verde ataca Vila de Leite."},"related":["sandro-livingstone"]},
{"id":"arautos-do-eclipse","title":"Arautos do Eclipse","type":"Campanha","region":"Geral","status":"CANON","summary":"Campanha canonizada que substitui referências antigas a 'Arautos do Crepúsculo'.","aliases":["Arautos do Crepúsculo (nome antigo/obsoleto)"],"tags":["campanha","corellian"],"sections":{"Eventos":"Inclui Corellian em chamas, conflitos com Rocha do Leopardo, a missão em Escarpa Negra e a incorporação de Giss."},"related":["corellian","escarpa-negra","fuuma"]},
{"id":"fora-do-domo","title":"Fora do Domo","type":"Campanha","region":"Geral","status":"CANON","summary":"Campanha situada em 1492, quando a Pedra do Mundo completa permite o resgate de Astelia.","aliases":[],"tags":["campanha","1492","astelia"],"sections":{"Marco":"Escarpa Negra funciona como polo militar antes de Brent assumir esse papel. A reunião da Pedra do Mundo permite o resgate de Astelia."},"related":["nova-astelia","pedra-do-mundo","escarpa-negra","brent"]}
]);
